spring:
  datasource:
     url :  jdbc:h2:tcp://localhost/~/test
     username : sa
     password :
     driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings : false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jdbc:
    url :

logging level:
  org.hibernate.SQL : debug
